### ISSUE TITLE
dialog-confirm / dialog-dismiss not working.

### ISSUE THREAD

**Issue by psrivongse** [motss/jv-datepicker#1]
These to buttons do not seem to work. If I don't specify modal, I can click the overlay and it will get dismissed. I can create a simple paper-dialog and it works out fine with dialog-confirm/dialog-dismiss.

Polymer 1.1.3
paper-elements~1.0.5

**Comment by motss** [comment]
Could you please further elaborate your issue? For dialogs, unless you specify the attribute `modal` clicking on the overlay and/ or buttons with `dialog-confirm` or `dialog-dismiss` will close the dialog. Only modal dialog requires you to perform an action to close the dialog.

**Comment by motss** [comment]
Closing issue. Redesigning the element.
