### ISSUE TITLE
Styling font-size of clickable dates

### ISSUE THREAD

**Issue by nicholaswmin** [motss/jv-datepicker#11]
Is there any way to change the font-size of the dates? 
I've seen there's a bunch of styling properties but they all seem to deal with colors.

I'm talking about these date `div`s:

![screen shot 2016-04-16 at 18 38 02](https://cloud.githubusercontent.com/assets/3926463/14581925/9fd01172-0402-11e6-8007-a973a135a8c0.png)

**Comment by motss** [comment]
@nicholaswmin This can be fixed. A custom property can be added. By the way, what font size do you think it's more suitable (Might consider changing it to default font size)?

**Comment by nicholaswmin** [comment]
@motss I'd say at least 14px - Wondering what the Material Design guidelines are on this.

**Comment by motss** [comment]
> Also, do you think it would make sense to use em instead of px for all font-sizes to keep everything relative to a host font-size?
Since most of the things in Polymer use `px` I would say keep using `px` for now and I'm not sure how `em` would affect the overall visual experience.

Other than that, working on the font size issue you pointed out. Like I said, feel free to open issue or discuss about things you would like to see to improve this element. :smile:

**Comment by motss** [comment]
@nicholaswmin Would you mind help me picking one that looks better than the current one?
I personally prefer 2.

1. <image src="https://cloud.githubusercontent.com/assets/10607759/14585866/d83c5a1a-04b7-11e6-97ca-0e4a1cf16edc.png" alt=""></image>
2. ![datepicker-px-font-size](https://cloud.githubusercontent.com/assets/10607759/14585867/d83d1eb4-04b7-11e6-950a-356c6912dca4.png)
3. ![datepicker-px-font-size](https://cloud.githubusercontent.com/assets/10607759/14585865/d83b1b8c-04b7-11e6-94fa-21992ea3ab7a.png)

**Comment by nicholaswmin** [comment]
> Since most of the things in Polymer use px I would say keep using px for
now and I'm not sure how em would affect the overall visual experience.

Makes sense:)

2 is my choice as well.

**Comment by motss** [comment]
@nicholaswmin Thanks. The fix is OTW.

**Comment by nicholaswmin** [comment]
Any ETA on a release for this? 

I'm on bower.

**Comment by motss** [comment]
@nicholaswmin I'll release it the next day.
