### ISSUE TITLE
Consider debouncing the month-switching animations 

### ISSUE THREAD

**Issue by nicholaswmin** [motss/jv-datepicker#12]
- The month-switching animations make month-switching UX slow. Most people just frantically tap/click "prev/next" to switch to the month they want. 
- The animations make this kind of clunky. Each animation cycle needs to finish before the next tap/click on "prev/next" can take place.

Personally I'd do this:

- The animation could take place 150ms (could be a user specified custom prop) after the *last* previous/next tap/click. A [debouncer](https://css-tricks.com/the-difference-between-throttling-and-debouncing/) can be used here. There's a [debounce() utility method provided by Polymer itself](https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html).

---

I might be able to take this on and submit a PR when things clear up on my end.

**Comment by motss** [comment]
@nicholaswmin Looking forward to your PR. :+1:

**Comment by motss** [comment]
@nicholaswmin Released 14d572f170f95fbec0df5547b9f246758edd06c5
