### ISSUE TITLE
Vulcanizing datepicker causes bug

### ISSUE THREAD

**Issue by eddier** [motss/jv-datepicker#5]
When you vulcanize the datepicker component the action attribute is rewritten which breaks the ability to go forward in the calendar.  

We made a fix on our side to deal with it until Polymer updates Vulcanize.  If you want a PR for it I can send it over.

https://github.com/Polymer/vulcanize/issues/294

**Comment by motss** [comment]
@eddier You're more than welcome to send in a PR. :smiley:

**Comment by eddier** [comment]
sent https://github.com/motss/jv-datepicker/pull/6

**Comment by FLamparski** [comment]
@motss Hi, when are you merging this?

**Comment by motss** [comment]
@FLamparski I'm currently working on a few improvements alongside this patch. I can merge this first ATM.
