### ISSUE TITLE
Setting datepicker.date from outside of the date picker dialog is ignored

### ISSUE THREAD

**Issue by FLamparski** [motss/jv-datepicker#7]
I want a combo date picker box: a datepicker-dialog that lets me pick the date from the calendar, and a text entry field for people who don't care for things like that and just want to enter a date from their keyboard. The problem is that what if they entered a date from the keyboard, but then want to correct it on the graphical picker?

At the moment, it's not possible to do so because setting `date` on the datepicker is completely ignored. I noticed that datepicker-dialog is pass-through in terms of the date, but the datepicker itself only uses the date on startup.

**Comment by motss** [comment]
@FLamparski It's because the `date` is designed to just read data from the selected date from the datepicker. I will work on this to allow user to change the `date` from the external so that the result will reflect on the datepicker.

**Comment by motss** [comment]
@FLamparski Please check the demo and see if the new implementation is what you have been looking for.

**Comment by motss** [comment]
@FLamparski I've update the demo page with the newly added `inputDate` property which can allow you to change the date without selecting any date on the datepicker. Just type the date at the `paper-input right below the datepicker and see the result.

**Comment by motss** [comment]
@FLamparski Closing this and feel free to reopen if the issue still persists.
